description: "Мета-сущности"
get:
    description: "Получть список сущностей"
    is: !include /../../../vendor/yii2bundle/yii2-rest/src/domain/docs/is/all.raml
    responses:
        200:
            body:
                application/json:
                    example: !include example/all-response-body.json
/{id}:
    uriParameters:
        id:
            description: "ID сущности"
            type: integer
    get:
        description: "Получить сущность"
        is: !include /../../../vendor/yii2bundle/yii2-rest/src/domain/docs/is/one.raml
        responses:
            200:
                body:
                    application/json:
                        example: !include example/one-response-body.json
    put:
        securedBy: [Auth]
        description: "Валидация данных сущности"
        is: !include /../../../vendor/yii2bundle/yii2-rest/src/domain/docs/is/update.raml
        body:
            application/json:
                example: !include example/update-request-body.json